spring:
  application:
    name: mobvoi-demo
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://10.112.170.192:3306/bxz-demo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: IWEkzXvG5940
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8080
# ops端口？

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.bxz.entity
  configuration:
    mapUnderscoreToCamelCase: true
endpoints:
  shutdown:
    enabled: true
##暴露监控端口
management:
  port: 8081
  context-path: /ops

---
spring:
 profiles: dev

---
 spring:
  profiles: docker